package Arithmetic;


/**
* Arithmetic/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ArithmeticOperations.idl
* Saturday, February 17, 2024 6:51:06 PM IST
*/

public interface CalculatorOperations 
{
  float add (float operand1, float operand2);
  float subtract (float operand1, float operand2);
  float multiply (float operand1, float operand2);
  float divide (float operand1, float operand2);
} // interface CalculatorOperations
