package Arithmetic;


/**
* Arithmetic/Calculator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ArithmeticOperations.idl
* Saturday, February 17, 2024 6:51:06 PM IST
*/

public interface Calculator extends CalculatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculator
