package Arithmetic;


/**
* Arithmetic/CalculatorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ArithmeticOperations.idl
* Saturday, February 17, 2024 6:51:06 PM IST
*/

abstract public class CalculatorHelper
{
  private static String  _id = "IDL:Arithmetic/Calculator:1.0";

  public static void insert (org.omg.CORBA.Any a, Arithmetic.Calculator that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Arithmetic.Calculator extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Arithmetic.CalculatorHelper.id (), "Calculator");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Arithmetic.Calculator read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CalculatorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Arithmetic.Calculator value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Arithmetic.Calculator narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Arithmetic.Calculator)
      return (Arithmetic.Calculator)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Arithmetic._CalculatorStub stub = new Arithmetic._CalculatorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Arithmetic.Calculator unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Arithmetic.Calculator)
      return (Arithmetic.Calculator)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Arithmetic._CalculatorStub stub = new Arithmetic._CalculatorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
